language: rust
rust:
  - nightly
#  - beta
#  - 1.0.0
sudo: false
after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=handlebars/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
