[package]

name = "handlebars"
version = "0.9.0"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templating", "web"]
homepage = "https://github.com/sunng87/handlebars-rust"
repository = "https://github.com/sunng87/handlebars-rust"
documentation = "http://sunng.info/handlebars-rust/"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"

[dependencies]

regex = "*"
log = "*"
rustc-serialize = "*"
num = "*"

[dev-dependencies]
env_logger = "*"
maplit = "*"
#tojson_macros = "*"
