[package]

name = "handlebars"
version = "0.2.0"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templates", "web"]
repository = "https://github.com/sunng87/handlebars-rust"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"
