[package]

name = "handlebars"
version = "0.22.1-pre"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templating", "web"]
homepage = "https://github.com/sunng87/handlebars-rust"
repository = "https://github.com/sunng87/handlebars-rust"
documentation = "http://sunng87.github.io/handlebars-rust/"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"

[dependencies]

log = "^0.3.1"
quick-error = "^1.0.0"
pest = "^0.3.0"
serde_json = { version = "^0.8.0", optional = true }
rustc-serialize = { version = "^0.3.15", optional = true }

serde = { version = "^0.8.0", optional = true }
serde_derive = { version = "^0.8.10", optional = true }

[features]
default = ["rustc_ser_type"]
rustc_ser_type = ["rustc-serialize"]
serde_type = ["serde_json"]
unstable = ["serde_type", "serde", "serde_derive"]
partial4 = []

[dev-dependencies]
env_logger = "^0.3.2"
maplit = "^0.1.3"
#tojson_macros = "*"
#syntex = "*"

[package.metadata.release]
sign-commit = true
upload-doc = true
